//****************SEASONS****************//
//****************TEAMS****************//

###
GET http://localhost:3000/api/f1/teams

###
GET http://localhost:3000/api/f1/teams?page=0&size=4

###
POST http://localhost:3000/api/f1/teams
Content-Type: application/json

{
    "team": "prueba",
    "year_foundation": 1970,
    "driver1": "Lewis Hamilton",
    "driver2": "Valtteri Bottas",
    "team_chief": "Toto Wolff"
}

###
GET http://localhost:3000/api/f1/teams/5fe139349b251a085807233d

###
DELETE http://localhost:3000/api/f1/teams/5fe139349b251a085807233d

###
PUT http://localhost:3000/api/f1/teams/5fe13bd97078e9088820bed9
Content-Type: application/json

{
    "team": "Aston Martin Red Bull Racing"
}



//****************DRIVERS****************//
###
GET http://localhost:3000/api/f1/drivers

###
GET http://localhost:3000/api/f1/drivers?page=0&size=4


###
POST http://localhost:3000/api/f1/drivers
Content-Type: application/json

{
    "name": "demooo",
    "team": "BWT Racing Point F1 Team",
    "country": "Mexico",
    "date_birth": "26/01/1990"
}

###
GET http://localhost:3000/api/f1/drivers/5fe139c29b251a085807233e

###
DELETE http://localhost:3000/api/f1/drivers/5fe139c29b251a085807233e

###
PUT http://localhost:3000/api/f1/drivers/5fdafa3a3cd984a7dd9228ef
Content-Type: application/json

{
    "country": "México"
}

###
//Pilotos campeones - pendiente
//GET http://localhost:3000/api/f1/drivers/champions



