//****************SEASONS****************//
//****************TEAMS****************//

###
GET http://localhost:3000/api/f1/teams

###
POST http://localhost:3000/api/f1/teams
Content-Type: application/json

{
    "team": "Scuderia Ferrari Mission Winnow",
    "year_foundation": 1950,
    "driver1": "Charles Leclerc",
    "driver2": "Sebastian Vettel",
    "team_chief": "Mattia Binotto"
}

###
GET http://localhost:3000/api/f1/

###
DELETE http://localhost:3000/api/f1/teams/

###
PUT http://localhost:3000/api/f1/teams/5fdb04c8818761accb1f84e5
Content-Type: application/json

{
    "team": "Scuderia Ferrari Mission Winnow"
}




//****************DRIVERS****************//
###
GET http://localhost:3000/api/f1/drivers

###
POST http://localhost:3000/api/f1/drivers
Content-Type: application/json

{
    "name": "Sainz",
    "team": "BWT Racing Point F1 Team",
    "country": "Mexico",
    "date_birth": "26/01/1990"
}

###
GET http://localhost:3000/api/f1/drivers/

###
DELETE http://localhost:3000/api/f1/drivers/5fdaff63a579c3aa97b77b2a

###
PUT http://localhost:3000/api/f1/drivers/5fdaff63a579c3aa97b77b2a
Content-Type: application/json

{
    "name": "Lance Stroll",
    "team": "BWT Racing Point F1 Team",
    "country": "Canada",
    "date_birth": "29/10/1998"
}

###
//Pilotos campeones pendiente
//GET http://localhost:3000/api/f1/drivers/champions



